# Generated by Django 2.2.6 on 2019-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('infix', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('photo', models.ImageField(default='', upload_to='')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=25)),
                ('company_photo', models.ImageField(default='', upload_to='')),
                ('company_address', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
    ]
